#!/bin/bash
# bye-reader start script
# chkconfig: 345 99 1
# description: uwsgi start script
# processname: uwsgi
# pidfile: /tmp/uwsgi.pid
#

# Source function library.
#. /etc/init.d/functions
. /lib/lsb/init-functions

PROGNAME="uwsgi"
PID="/tmp/$PROGNAME.pid"
LOCK="/tmp/$PROGNAME.lock"
RETVAL=0

UWSGI_BIN="/usr/local/bin/$PROGNAME"
APP_DIR="/home/vagrant"
UWSGI_LOG="/var/log/uwsgi/$PROGNAME.log"
UWSGI_APP_INIT="$APP_DIR/uwsgi.ini"

PROG=$UWSGI_BIN
SSD="/sbin/start-stop-daemon"

[ -f $PROG ] || exit 0

start() {
        echo -n "Starting $PROGNAME: $PROG"
        $SSD --start --quiet --background --retry 5 --oknodo --exec $PROG $UWSGI_APP_INIT -- --pidfile $PID
        log_end_msg $?
        [ $RETVAL = 0 ] && touch $LOCK
        return $RETVAL
}

stop() {
        echo -n "Stopping $PROGNAME: "
        $SSD --stop --quiet --pidfile $PID \
                        --retry 5 --oknodo --exec $PROG
        log_end_msg $?
        RETVAL=$?
        [ $RETVAL = 0 ] && rm -f $LOCK $PID
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        sleep 1
        start
        ;;

    status)
        status_of_proc -p $PID "$PROG" uwsgi
        ;;
    *)
        echo "Usage: $PROGNAME {start|stop|restart|status}"
        RETVAL=2
        ;;
esac

exit $RETVAL
