- name: start provisioning
  sudo: yes
  hosts: vagrant
  roles:
    - common
    - {role: jdauphant.nginx}
    - {role: gdamjan.uwsgi}
    - {
        role: vitalk.flaskapp,
        app_user: "{{ APP_USER_NAME}}"
}
