#!/bin/bash
#
# bye-reader start script
#
# chkconfig: 345 99 1
# description: uwsgi start script
# processname: uwsgi
# pidfile: /tmp/uwsgi.pid
#
# deploy to /etc/init.d/

# Source function library.
. /etc/init.d/functions

PROGNAME="uwsgi"
PID="/tmp/$PROGNAME.pid"
LOCK="/tmp/$PROGNAME.lock"
RETVAL=0

UWSGI_BIN="/usr/local/bin/uwsgi"
UWSGI_APP_DIR="/home/vagrant"
UWSGI_APP_BIN="$UWSGI_APP_DIR/deploy/current/source"
UWSGI_LOG="/var/log/uwsgi/$PROGNAME.log"
UWSGI_APP_INIT="$UWSGI_APP_DIR/uwsgi.ini"

PROG=$UWSGI_BIN

[ -f $PROG ] || exit 0

start() {
        echo -n "Starting $PROGNAME: "
        daemon $PROG $UWSGI_APP_INIT  --uid nginx --gid nginx -d $UWSGI_LOG --master --pidfile $PID
        echo
        [ $RETVAL = 0 ] && touch $LOCK
        return $RETVAL
}

stop() {
        echo -n "Stopping $PROGNAME: "
        killproc -p $PID $PROGNAME -INT
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && rm -f $LOCK $PID
}

show_status() {
        status $PROGNAME
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        show_status
        ;;
    *)
        echo "Usage: $PROGNAME {start|stop|restart|status}"
        RETVAL=2
        ;;
esac
exit $RETVAL
