---
- name: Install packages required for python development
  apt: pkg={{ item }} state=present
  sudo: true
  with_items:
    - git
    - libpq-dev
    - python-dev
    - python-psycopg2
    - python-virtualenv
    - build-essential

- name: Install the latest pip version
  pip: name=pip extra_args='-U'
  sudo: true

- name: Ensure the pip config directory is exist
  file:
    path=/home/{{ app_user }}/.pip
    owner={{ app_user }} group={{ app_user }} mode=0755
    state=directory

- name: Ensure the pip config file is exist
  file:
    path=/home/{{ app_user }}/.pip/pip.conf
    owner={{ app_user }} group={{ app_user }} mode=0644
    state=touch

- name: Ensure pip packages are cached
  lineinfile:
    dest=/home/{{ app_user }}/.pip/pip.conf
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - { regexp: '^\[global\]$', line: '[global]' }
    - { regexp: '^download_cache', line: 'download_cache = ~/.cache/pip' }
