- name: Deny everything and enable UFW
  ufw: state=enabled policy=deny

# Allow OpenSSH
- name: Allow ssh
  ufw: rule=allow name=OpenSSH

- name: Allow 80
  ufw: rule=allow port=80

- name: Allow 443
  ufw: rule=allow port=443
