---
- name: configure uwsgi.ini to home directory
  sudo: no
  template: src=uwsgi.ini.j2 dest=/home/{{ APP_USER_NAME }}/uwsgi_{{ APP_NAME }}.ini

- name: delete nginx default sites ( create by jdauphant.nginx)
  file: path=/etc/nginx/sites-enabled/default.conf state=absent

- name: configure uwsgi.ini to nginx
  template: src=uwsgi.conf.j2 dest=/etc/nginx/conf.d/{{ APP_NAME }}.conf

- name: create exec uwsgi app script to init
  template: src=uwsgi.init.conf.j2 dest=/etc/init/uwsgi_{{ APP_NAME }}.conf
