# Update all packages to the latest version
- name: Update packages
  apt: update_cache=yes

- name: Install packages required for python development
  apt: pkg={{ item }} state=present
  sudo: true
  with_items:
    - git
    - python-dev
    - python-virtualenv
    - build-essential
